import pandas as pd
import sys
import json
import csv
import collections


###############################################
"""
Script to be used with a non-standardized json
For instance: the IHEC json
"""
###############################################


def convert_json_csv(json_file,out_file):

    #get all keys to be headers
    headers = collections.OrderedDict(((key, None) for dict_ihec in json_file['datasets'] for key in dict_ihec)) 
    
    with open(out_file, 'w') as f:
        writer = csv.DictWriter(f, fieldnames=headers, delimiter='\t')
        #write the column names to file
        writer.writeheader()
        #wirte the data to file
        writer.writerows(json_file['datasets'])



def main():

    ihec_hg = json.load(open(sys.argv[1])) #ihec_json hg19 generated by epiatlas_2020.py 
    out_file = sys.argv[2]
    convert_json_csv(ihec_hg, out_file)

if __name__ == "__main__":


    main()