
import json
import csv
import sys

################################################################################
"""
Script to be used with a standardized json (all dicts have the same keys)
For instance: the EpiClass json
"""
################################################################################

def json_to_csv(json_metadata,output_name):

    dsets = json_metadata['datasets']

    #open csv file
    metadata_file = open(output_name, 'w')
    
    #csv writer
    csv_writer = csv.writer(metadata_file,delimiter='\t')

    #counter used for wirting the header
    count = 0
    
    for dset in dsets:
        if count == 0:
            header = dset.keys() #to be columns - keys from each dset
            csv_writer.writerow(header)
            count +=1
    
        #writing data to the csv
        csv_writer.writerow(dset.values())

    metadata_file.close()



def main():

    json_metadata = json.load(open(sys.argv[1])) #json_metadata generated by epiatlas_2020.py + merged json
    output_name = sys.argv[2]
    json_to_csv(json_metadata, output_name)


if __name__ == "__main__":



    main()